queue_rules:
  - name: default
    queue_conditions:
      - base=master
      - author=dependabot[bot]
      - label!=major
      - label=automerge
    merge_conditions:
      # Conditions to get out of the queue (= merged)
      - label=automerge
      - label=workflow-bump
    merge_method: squash

pull_request_rules:
  - name: approve dependabot
    conditions:
      - author=dependabot[bot]
    actions:
      review:
        message: 'Thanks Dependabot! :rocket:'
  - name: refactored queue action rule
    conditions: []
    actions:
      queue:
