name: Build pkg x64

on:
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  build:
    name: Build package and attach to release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v5

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install and pre-build
        run: |
          npm ci
          npm run build

      - name: Build for x64
        run: |
          npm run pkg -- --bundle --skip-build

      - name: Upload artifacts
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: pkg-build
          path: ./build/pkg/*.zip

      - name: Upload binaries to release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./build/pkg/*.zip
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true
