name: Test Application

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    test-e2e:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v5

            - name: Set up Node.js
              uses: actions/setup-node@v5
              with:
                  node-version-file: '.nvmrc'
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Build backend
              run: npm run build:server

            - name: Test application
              uses: ./.github/actions/e2e
              with:
                  start-command: npm start
